sudo: false
language: php
php:
    - 7.4

services:
    - mongodb

before_script:
    - composer self-update
    - composer install --ignore-platform-reqs
    - pecl channel-update pecl.php.net
    - pecl install mongodb

script:
    - ./vendor/bin/phpunit --configuration ./test/phpunit.xml