sudo: false
language: php
php:
    - 7.4

services:
    - mongodb

before_script:
    #- pecl channel-update pecl.php.net
    #- pecl install mongodb
    - composer self-update
    - composer install

script:
    - ./vendor/bin/phpunit --configuration ./test/phpunit.xml