sudo: false
language: php
php:
    - 8.0snapshot
    - nightly

services:
    - mongodb

before_script:
    - pecl channel-update pecl.php.net
    - pecl uninstall mongodb
    - pecl install mongodb
    - composer self-update
    - composer install

script:
    - ./vendor/bin/phpunit --configuration ./test/phpunit.xml