sudo: false
language: php
php:
    - 7.4

services:
    - redis-server

before_script:
    - composer self-update
    - composer install --ignore-platform-reqs

script:
    - ./vendor/bin/phpunit --configuration ./test/phpunit.xml